### YamlMime:ManagedReference
items:
- uid: Quickie.Configuration.Idempotency.DefaultProvider
  commentId: N:Quickie.Configuration.Idempotency.DefaultProvider
  id: Quickie.Configuration.Idempotency.DefaultProvider
  children:
  - Quickie.Configuration.Idempotency.DefaultProvider.InMemoryIdempotencyProvider
  langs:
  - csharp
  - vb
  name: Quickie.Configuration.Idempotency.DefaultProvider
  nameWithType: Quickie.Configuration.Idempotency.DefaultProvider
  fullName: Quickie.Configuration.Idempotency.DefaultProvider
  type: Namespace
  assemblies:
  - Quickie
references:
- uid: Quickie.Configuration.Idempotency.DefaultProvider.InMemoryIdempotencyProvider
  commentId: T:Quickie.Configuration.Idempotency.DefaultProvider.InMemoryIdempotencyProvider
  href: Quickie.Configuration.Idempotency.DefaultProvider.InMemoryIdempotencyProvider.html
  name: InMemoryIdempotencyProvider
  nameWithType: InMemoryIdempotencyProvider
  fullName: Quickie.Configuration.Idempotency.DefaultProvider.InMemoryIdempotencyProvider
