### YamlMime:ManagedReference
items:
- uid: Quickie.Configuration.Options
  commentId: N:Quickie.Configuration.Options
  id: Quickie.Configuration.Options
  children:
  - Quickie.Configuration.Options.GlobalQuickieConfigData
  - Quickie.Configuration.Options.RateLimitConfiguration
  langs:
  - csharp
  - vb
  name: Quickie.Configuration.Options
  nameWithType: Quickie.Configuration.Options
  fullName: Quickie.Configuration.Options
  type: Namespace
  assemblies:
  - Quickie
references:
- uid: Quickie.Configuration.Options.GlobalQuickieConfigData
  commentId: T:Quickie.Configuration.Options.GlobalQuickieConfigData
  href: Quickie.Configuration.Options.GlobalQuickieConfigData.html
  name: GlobalQuickieConfigData
  nameWithType: GlobalQuickieConfigData
  fullName: Quickie.Configuration.Options.GlobalQuickieConfigData
- uid: Quickie.Configuration.Options.RateLimitConfiguration
  commentId: T:Quickie.Configuration.Options.RateLimitConfiguration
  parent: Quickie.Configuration.Options
  href: Quickie.Configuration.Options.RateLimitConfiguration.html
  name: RateLimitConfiguration
  nameWithType: RateLimitConfiguration
  fullName: Quickie.Configuration.Options.RateLimitConfiguration
- uid: Quickie.Configuration.Options
  commentId: N:Quickie.Configuration.Options
  href: Quickie.html
  name: Quickie.Configuration.Options
  nameWithType: Quickie.Configuration.Options
  fullName: Quickie.Configuration.Options
  spec.csharp:
  - uid: Quickie
    name: Quickie
    href: Quickie.html
  - name: .
  - uid: Quickie.Configuration
    name: Configuration
    href: Quickie.Configuration.html
  - name: .
  - uid: Quickie.Configuration.Options
    name: Options
    href: Quickie.Configuration.Options.html
  spec.vb:
  - uid: Quickie
    name: Quickie
    href: Quickie.html
  - name: .
  - uid: Quickie.Configuration
    name: Configuration
    href: Quickie.Configuration.html
  - name: .
  - uid: Quickie.Configuration.Options
    name: Options
    href: Quickie.Configuration.Options.html
