### YamlMime:ManagedReference
items:
- uid: Quickie.Configuration.Middleware.IdempotencyMiddleware
  commentId: T:Quickie.Configuration.Middleware.IdempotencyMiddleware
  id: IdempotencyMiddleware
  parent: Quickie.Configuration.Middleware
  children:
  - Quickie.Configuration.Middleware.IdempotencyMiddleware.#ctor(Quickie.Configuration.Idempotency.IIdempotencyProvider,Microsoft.AspNetCore.Http.RequestDelegate)
  - Quickie.Configuration.Middleware.IdempotencyMiddleware.InvokeAsync(Microsoft.AspNetCore.Http.HttpContext)
  langs:
  - csharp
  - vb
  name: IdempotencyMiddleware
  nameWithType: IdempotencyMiddleware
  fullName: Quickie.Configuration.Middleware.IdempotencyMiddleware
  type: Class
  source:
    remote:
      path: src/Quickie/Configuration/Middleware/IdempotencyMiddleware.cs
      branch: f-minimalapi
      repo: https://github.com/sushantpt/Quickie.git
    id: IdempotencyMiddleware
    path: ../src/Quickie/Configuration/Middleware/IdempotencyMiddleware.cs
    startLine: 9
  assemblies:
  - Quickie
  namespace: Quickie.Configuration.Middleware
  summary: Idempotency implementer middleware
  example: []
  syntax:
    content: public class IdempotencyMiddleware
    content.vb: Public Class IdempotencyMiddleware
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Quickie.Configuration.Middleware.IdempotencyMiddleware.#ctor(Quickie.Configuration.Idempotency.IIdempotencyProvider,Microsoft.AspNetCore.Http.RequestDelegate)
  commentId: M:Quickie.Configuration.Middleware.IdempotencyMiddleware.#ctor(Quickie.Configuration.Idempotency.IIdempotencyProvider,Microsoft.AspNetCore.Http.RequestDelegate)
  id: '#ctor(Quickie.Configuration.Idempotency.IIdempotencyProvider,Microsoft.AspNetCore.Http.RequestDelegate)'
  parent: Quickie.Configuration.Middleware.IdempotencyMiddleware
  langs:
  - csharp
  - vb
  name: IdempotencyMiddleware(IIdempotencyProvider, RequestDelegate)
  nameWithType: IdempotencyMiddleware.IdempotencyMiddleware(IIdempotencyProvider, RequestDelegate)
  fullName: Quickie.Configuration.Middleware.IdempotencyMiddleware.IdempotencyMiddleware(Quickie.Configuration.Idempotency.IIdempotencyProvider, Microsoft.AspNetCore.Http.RequestDelegate)
  type: Constructor
  source:
    remote:
      path: src/Quickie/Configuration/Middleware/IdempotencyMiddleware.cs
      branch: f-minimalapi
      repo: https://github.com/sushantpt/Quickie.git
    id: .ctor
    path: ../src/Quickie/Configuration/Middleware/IdempotencyMiddleware.cs
    startLine: 9
  assemblies:
  - Quickie
  namespace: Quickie.Configuration.Middleware
  summary: Idempotency implementer middleware
  example: []
  syntax:
    content: public IdempotencyMiddleware(IIdempotencyProvider idempotencyProvider, RequestDelegate next)
    parameters:
    - id: idempotencyProvider
      type: Quickie.Configuration.Idempotency.IIdempotencyProvider
      description: Idempotency provider
    - id: next
      type: Microsoft.AspNetCore.Http.RequestDelegate
      description: ''
    content.vb: Public Sub New(idempotencyProvider As IIdempotencyProvider, [next] As RequestDelegate)
  overload: Quickie.Configuration.Middleware.IdempotencyMiddleware.#ctor*
  nameWithType.vb: IdempotencyMiddleware.New(IIdempotencyProvider, RequestDelegate)
  fullName.vb: Quickie.Configuration.Middleware.IdempotencyMiddleware.New(Quickie.Configuration.Idempotency.IIdempotencyProvider, Microsoft.AspNetCore.Http.RequestDelegate)
  name.vb: New(IIdempotencyProvider, RequestDelegate)
- uid: Quickie.Configuration.Middleware.IdempotencyMiddleware.InvokeAsync(Microsoft.AspNetCore.Http.HttpContext)
  commentId: M:Quickie.Configuration.Middleware.IdempotencyMiddleware.InvokeAsync(Microsoft.AspNetCore.Http.HttpContext)
  id: InvokeAsync(Microsoft.AspNetCore.Http.HttpContext)
  parent: Quickie.Configuration.Middleware.IdempotencyMiddleware
  langs:
  - csharp
  - vb
  name: InvokeAsync(HttpContext)
  nameWithType: IdempotencyMiddleware.InvokeAsync(HttpContext)
  fullName: Quickie.Configuration.Middleware.IdempotencyMiddleware.InvokeAsync(Microsoft.AspNetCore.Http.HttpContext)
  type: Method
  source:
    remote:
      path: src/Quickie/Configuration/Middleware/IdempotencyMiddleware.cs
      branch: f-minimalapi
      repo: https://github.com/sushantpt/Quickie.git
    id: InvokeAsync
    path: ../src/Quickie/Configuration/Middleware/IdempotencyMiddleware.cs
    startLine: 11
  assemblies:
  - Quickie
  namespace: Quickie.Configuration.Middleware
  syntax:
    content: public Task InvokeAsync(HttpContext context)
    parameters:
    - id: context
      type: Microsoft.AspNetCore.Http.HttpContext
    return:
      type: System.Threading.Tasks.Task
    content.vb: Public Function InvokeAsync(context As HttpContext) As Task
  overload: Quickie.Configuration.Middleware.IdempotencyMiddleware.InvokeAsync*
references:
- uid: Quickie.Configuration.Middleware
  commentId: N:Quickie.Configuration.Middleware
  href: Quickie.html
  name: Quickie.Configuration.Middleware
  nameWithType: Quickie.Configuration.Middleware
  fullName: Quickie.Configuration.Middleware
  spec.csharp:
  - uid: Quickie
    name: Quickie
    href: Quickie.html
  - name: .
  - uid: Quickie.Configuration
    name: Configuration
    href: Quickie.Configuration.html
  - name: .
  - uid: Quickie.Configuration.Middleware
    name: Middleware
    href: Quickie.Configuration.Middleware.html
  spec.vb:
  - uid: Quickie
    name: Quickie
    href: Quickie.html
  - name: .
  - uid: Quickie.Configuration
    name: Configuration
    href: Quickie.Configuration.html
  - name: .
  - uid: Quickie.Configuration.Middleware
    name: Middleware
    href: Quickie.Configuration.Middleware.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Quickie.Configuration.Middleware.IdempotencyMiddleware.#ctor*
  commentId: Overload:Quickie.Configuration.Middleware.IdempotencyMiddleware.#ctor
  href: Quickie.Configuration.Middleware.IdempotencyMiddleware.html#Quickie_Configuration_Middleware_IdempotencyMiddleware__ctor_Quickie_Configuration_Idempotency_IIdempotencyProvider_Microsoft_AspNetCore_Http_RequestDelegate_
  name: IdempotencyMiddleware
  nameWithType: IdempotencyMiddleware.IdempotencyMiddleware
  fullName: Quickie.Configuration.Middleware.IdempotencyMiddleware.IdempotencyMiddleware
  nameWithType.vb: IdempotencyMiddleware.New
  fullName.vb: Quickie.Configuration.Middleware.IdempotencyMiddleware.New
  name.vb: New
- uid: Quickie.Configuration.Idempotency.IIdempotencyProvider
  commentId: T:Quickie.Configuration.Idempotency.IIdempotencyProvider
  parent: Quickie.Configuration.Idempotency
  href: Quickie.Configuration.Idempotency.IIdempotencyProvider.html
  name: IIdempotencyProvider
  nameWithType: IIdempotencyProvider
  fullName: Quickie.Configuration.Idempotency.IIdempotencyProvider
- uid: Microsoft.AspNetCore.Http.RequestDelegate
  commentId: T:Microsoft.AspNetCore.Http.RequestDelegate
  parent: Microsoft.AspNetCore.Http
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore.http.requestdelegate
  name: RequestDelegate
  nameWithType: RequestDelegate
  fullName: Microsoft.AspNetCore.Http.RequestDelegate
- uid: Quickie.Configuration.Idempotency
  commentId: N:Quickie.Configuration.Idempotency
  href: Quickie.html
  name: Quickie.Configuration.Idempotency
  nameWithType: Quickie.Configuration.Idempotency
  fullName: Quickie.Configuration.Idempotency
  spec.csharp:
  - uid: Quickie
    name: Quickie
    href: Quickie.html
  - name: .
  - uid: Quickie.Configuration
    name: Configuration
    href: Quickie.Configuration.html
  - name: .
  - uid: Quickie.Configuration.Idempotency
    name: Idempotency
    href: Quickie.Configuration.Idempotency.html
  spec.vb:
  - uid: Quickie
    name: Quickie
    href: Quickie.html
  - name: .
  - uid: Quickie.Configuration
    name: Configuration
    href: Quickie.Configuration.html
  - name: .
  - uid: Quickie.Configuration.Idempotency
    name: Idempotency
    href: Quickie.Configuration.Idempotency.html
- uid: Microsoft.AspNetCore.Http
  commentId: N:Microsoft.AspNetCore.Http
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft
  name: Microsoft.AspNetCore.Http
  nameWithType: Microsoft.AspNetCore.Http
  fullName: Microsoft.AspNetCore.Http
  spec.csharp:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.AspNetCore
    name: AspNetCore
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore
  - name: .
  - uid: Microsoft.AspNetCore.Http
    name: Http
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore.http
  spec.vb:
  - uid: Microsoft
    name: Microsoft
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft
  - name: .
  - uid: Microsoft.AspNetCore
    name: AspNetCore
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore
  - name: .
  - uid: Microsoft.AspNetCore.Http
    name: Http
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore.http
- uid: Quickie.Configuration.Middleware.IdempotencyMiddleware.InvokeAsync*
  commentId: Overload:Quickie.Configuration.Middleware.IdempotencyMiddleware.InvokeAsync
  href: Quickie.Configuration.Middleware.IdempotencyMiddleware.html#Quickie_Configuration_Middleware_IdempotencyMiddleware_InvokeAsync_Microsoft_AspNetCore_Http_HttpContext_
  name: InvokeAsync
  nameWithType: IdempotencyMiddleware.InvokeAsync
  fullName: Quickie.Configuration.Middleware.IdempotencyMiddleware.InvokeAsync
- uid: Microsoft.AspNetCore.Http.HttpContext
  commentId: T:Microsoft.AspNetCore.Http.HttpContext
  parent: Microsoft.AspNetCore.Http
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/microsoft.aspnetcore.http.httpcontext
  name: HttpContext
  nameWithType: HttpContext
  fullName: Microsoft.AspNetCore.Http.HttpContext
- uid: System.Threading.Tasks.Task
  commentId: T:System.Threading.Tasks.Task
  parent: System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.threading.tasks.task
  name: Task
  nameWithType: Task
  fullName: System.Threading.Tasks.Task
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
  spec.csharp:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
  spec.vb:
  - uid: System
    name: System
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system
  - name: .
  - uid: System.Threading
    name: Threading
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading
  - name: .
  - uid: System.Threading.Tasks
    name: Tasks
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.threading.tasks
