### YamlMime:ManagedReference
items:
- uid: Quickie.Configuration.Options.RateLimitConfiguration
  commentId: T:Quickie.Configuration.Options.RateLimitConfiguration
  id: RateLimitConfiguration
  parent: Quickie.Configuration.Options
  children:
  - Quickie.Configuration.Options.RateLimitConfiguration.DisableRateLimiting
  - Quickie.Configuration.Options.RateLimitConfiguration.FromSeconds
  - Quickie.Configuration.Options.RateLimitConfiguration.PermitLimit
  - Quickie.Configuration.Options.RateLimitConfiguration.PolicyName
  langs:
  - csharp
  - vb
  name: RateLimitConfiguration
  nameWithType: RateLimitConfiguration
  fullName: Quickie.Configuration.Options.RateLimitConfiguration
  type: Class
  source:
    remote:
      path: src/Quickie/Configuration/Options/RateLimitConfiguration.cs
      branch: f-minimalapi
      repo: https://github.com/sushantpt/Quickie.git
    id: RateLimitConfiguration
    path: ../src/Quickie/Configuration/Options/RateLimitConfiguration.cs
    startLine: 5
  assemblies:
  - Quickie
  namespace: Quickie.Configuration.Options
  summary: Rate limit configuration. (ip based)
  example: []
  syntax:
    content: public class RateLimitConfiguration
    content.vb: Public Class RateLimitConfiguration
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: Quickie.Configuration.Options.RateLimitConfiguration.DisableRateLimiting
  commentId: P:Quickie.Configuration.Options.RateLimitConfiguration.DisableRateLimiting
  id: DisableRateLimiting
  parent: Quickie.Configuration.Options.RateLimitConfiguration
  langs:
  - csharp
  - vb
  name: DisableRateLimiting
  nameWithType: RateLimitConfiguration.DisableRateLimiting
  fullName: Quickie.Configuration.Options.RateLimitConfiguration.DisableRateLimiting
  type: Property
  source:
    remote:
      path: src/Quickie/Configuration/Options/RateLimitConfiguration.cs
      branch: f-minimalapi
      repo: https://github.com/sushantpt/Quickie.git
    id: DisableRateLimiting
    path: ../src/Quickie/Configuration/Options/RateLimitConfiguration.cs
    startLine: 10
  assemblies:
  - Quickie
  namespace: Quickie.Configuration.Options
  summary: Disable rate limiting. By default, rate limiting is <code>true</code>.
  example: []
  syntax:
    content: public bool DisableRateLimiting { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property DisableRateLimiting As Boolean
  overload: Quickie.Configuration.Options.RateLimitConfiguration.DisableRateLimiting*
- uid: Quickie.Configuration.Options.RateLimitConfiguration.PolicyName
  commentId: P:Quickie.Configuration.Options.RateLimitConfiguration.PolicyName
  id: PolicyName
  parent: Quickie.Configuration.Options.RateLimitConfiguration
  langs:
  - csharp
  - vb
  name: PolicyName
  nameWithType: RateLimitConfiguration.PolicyName
  fullName: Quickie.Configuration.Options.RateLimitConfiguration.PolicyName
  type: Property
  source:
    remote:
      path: src/Quickie/Configuration/Options/RateLimitConfiguration.cs
      branch: f-minimalapi
      repo: https://github.com/sushantpt/Quickie.git
    id: PolicyName
    path: ../src/Quickie/Configuration/Options/RateLimitConfiguration.cs
    startLine: 14
  assemblies:
  - Quickie
  namespace: Quickie.Configuration.Options
  summary: Name of rate limit policy. Default is "Quickie-Rl-Policy"
  example: []
  syntax:
    content: public string? PolicyName { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property PolicyName As String
  overload: Quickie.Configuration.Options.RateLimitConfiguration.PolicyName*
- uid: Quickie.Configuration.Options.RateLimitConfiguration.PermitLimit
  commentId: P:Quickie.Configuration.Options.RateLimitConfiguration.PermitLimit
  id: PermitLimit
  parent: Quickie.Configuration.Options.RateLimitConfiguration
  langs:
  - csharp
  - vb
  name: PermitLimit
  nameWithType: RateLimitConfiguration.PermitLimit
  fullName: Quickie.Configuration.Options.RateLimitConfiguration.PermitLimit
  type: Property
  source:
    remote:
      path: src/Quickie/Configuration/Options/RateLimitConfiguration.cs
      branch: f-minimalapi
      repo: https://github.com/sushantpt/Quickie.git
    id: PermitLimit
    path: ../src/Quickie/Configuration/Options/RateLimitConfiguration.cs
    startLine: 18
  assemblies:
  - Quickie
  namespace: Quickie.Configuration.Options
  summary: "Number of request. Default is: 1 request every 'FromSeconds'"
  example: []
  syntax:
    content: public int? PermitLimit { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.Int32}
    content.vb: Public Property PermitLimit As Integer?
  overload: Quickie.Configuration.Options.RateLimitConfiguration.PermitLimit*
- uid: Quickie.Configuration.Options.RateLimitConfiguration.FromSeconds
  commentId: P:Quickie.Configuration.Options.RateLimitConfiguration.FromSeconds
  id: FromSeconds
  parent: Quickie.Configuration.Options.RateLimitConfiguration
  langs:
  - csharp
  - vb
  name: FromSeconds
  nameWithType: RateLimitConfiguration.FromSeconds
  fullName: Quickie.Configuration.Options.RateLimitConfiguration.FromSeconds
  type: Property
  source:
    remote:
      path: src/Quickie/Configuration/Options/RateLimitConfiguration.cs
      branch: f-minimalapi
      repo: https://github.com/sushantpt/Quickie.git
    id: FromSeconds
    path: ../src/Quickie/Configuration/Options/RateLimitConfiguration.cs
    startLine: 22
  assemblies:
  - Quickie
  namespace: Quickie.Configuration.Options
  summary: 'Duration (seconds) to block. Default is: 6'
  example: []
  syntax:
    content: public int? FromSeconds { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.Int32}
    content.vb: Public Property FromSeconds As Integer?
  overload: Quickie.Configuration.Options.RateLimitConfiguration.FromSeconds*
references:
- uid: Quickie.Configuration.Options
  commentId: N:Quickie.Configuration.Options
  href: Quickie.html
  name: Quickie.Configuration.Options
  nameWithType: Quickie.Configuration.Options
  fullName: Quickie.Configuration.Options
  spec.csharp:
  - uid: Quickie
    name: Quickie
    href: Quickie.html
  - name: .
  - uid: Quickie.Configuration
    name: Configuration
    href: Quickie.Configuration.html
  - name: .
  - uid: Quickie.Configuration.Options
    name: Options
    href: Quickie.Configuration.Options.html
  spec.vb:
  - uid: Quickie
    name: Quickie
    href: Quickie.html
  - name: .
  - uid: Quickie.Configuration
    name: Configuration
    href: Quickie.Configuration.html
  - name: .
  - uid: Quickie.Configuration.Options
    name: Options
    href: Quickie.Configuration.Options.html
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: Quickie.Configuration.Options.RateLimitConfiguration.DisableRateLimiting*
  commentId: Overload:Quickie.Configuration.Options.RateLimitConfiguration.DisableRateLimiting
  href: Quickie.Configuration.Options.RateLimitConfiguration.html#Quickie_Configuration_Options_RateLimitConfiguration_DisableRateLimiting
  name: DisableRateLimiting
  nameWithType: RateLimitConfiguration.DisableRateLimiting
  fullName: Quickie.Configuration.Options.RateLimitConfiguration.DisableRateLimiting
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: Quickie.Configuration.Options.RateLimitConfiguration.PolicyName*
  commentId: Overload:Quickie.Configuration.Options.RateLimitConfiguration.PolicyName
  href: Quickie.Configuration.Options.RateLimitConfiguration.html#Quickie_Configuration_Options_RateLimitConfiguration_PolicyName
  name: PolicyName
  nameWithType: RateLimitConfiguration.PolicyName
  fullName: Quickie.Configuration.Options.RateLimitConfiguration.PolicyName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: Quickie.Configuration.Options.RateLimitConfiguration.PermitLimit*
  commentId: Overload:Quickie.Configuration.Options.RateLimitConfiguration.PermitLimit
  href: Quickie.Configuration.Options.RateLimitConfiguration.html#Quickie_Configuration_Options_RateLimitConfiguration_PermitLimit
  name: PermitLimit
  nameWithType: RateLimitConfiguration.PermitLimit
  fullName: Quickie.Configuration.Options.RateLimitConfiguration.PermitLimit
- uid: System.Nullable{System.Int32}
  commentId: T:System.Nullable{System.Int32}
  parent: System
  definition: System.Nullable`1
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int?
  nameWithType: int?
  fullName: int?
  nameWithType.vb: Integer?
  fullName.vb: Integer?
  name.vb: Integer?
  spec.csharp:
  - uid: System.Int32
    name: int
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: '?'
  spec.vb:
  - uid: System.Int32
    name: Integer
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int32
  - name: '?'
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: Quickie.Configuration.Options.RateLimitConfiguration.FromSeconds*
  commentId: Overload:Quickie.Configuration.Options.RateLimitConfiguration.FromSeconds
  href: Quickie.Configuration.Options.RateLimitConfiguration.html#Quickie_Configuration_Options_RateLimitConfiguration_FromSeconds
  name: FromSeconds
  nameWithType: RateLimitConfiguration.FromSeconds
  fullName: Quickie.Configuration.Options.RateLimitConfiguration.FromSeconds
