### YamlMime:ManagedReference
items:
- uid: Quickie.Configuration.Idempotency
  commentId: N:Quickie.Configuration.Idempotency
  id: Quickie.Configuration.Idempotency
  children:
  - Quickie.Configuration.Idempotency.IIdempotencyProvider
  - Quickie.Configuration.Idempotency.IdempotencyBackgroundService
  - Quickie.Configuration.Idempotency.IdempotentConfiguration
  langs:
  - csharp
  - vb
  name: Quickie.Configuration.Idempotency
  nameWithType: Quickie.Configuration.Idempotency
  fullName: Quickie.Configuration.Idempotency
  type: Namespace
  assemblies:
  - Quickie
references:
- uid: Quickie.Configuration.Idempotency.IdempotencyBackgroundService
  commentId: T:Quickie.Configuration.Idempotency.IdempotencyBackgroundService
  href: Quickie.Configuration.Idempotency.IdempotencyBackgroundService.html
  name: IdempotencyBackgroundService
  nameWithType: IdempotencyBackgroundService
  fullName: Quickie.Configuration.Idempotency.IdempotencyBackgroundService
- uid: Quickie.Configuration.Idempotency.IdempotentConfiguration
  commentId: T:Quickie.Configuration.Idempotency.IdempotentConfiguration
  parent: Quickie.Configuration.Idempotency
  href: Quickie.Configuration.Idempotency.IdempotentConfiguration.html
  name: IdempotentConfiguration
  nameWithType: IdempotentConfiguration
  fullName: Quickie.Configuration.Idempotency.IdempotentConfiguration
- uid: Quickie.Configuration.Idempotency.IIdempotencyProvider
  commentId: T:Quickie.Configuration.Idempotency.IIdempotencyProvider
  parent: Quickie.Configuration.Idempotency
  href: Quickie.Configuration.Idempotency.IIdempotencyProvider.html
  name: IIdempotencyProvider
  nameWithType: IIdempotencyProvider
  fullName: Quickie.Configuration.Idempotency.IIdempotencyProvider
- uid: Quickie.Configuration.Idempotency
  commentId: N:Quickie.Configuration.Idempotency
  href: Quickie.html
  name: Quickie.Configuration.Idempotency
  nameWithType: Quickie.Configuration.Idempotency
  fullName: Quickie.Configuration.Idempotency
  spec.csharp:
  - uid: Quickie
    name: Quickie
    href: Quickie.html
  - name: .
  - uid: Quickie.Configuration
    name: Configuration
    href: Quickie.Configuration.html
  - name: .
  - uid: Quickie.Configuration.Idempotency
    name: Idempotency
    href: Quickie.Configuration.Idempotency.html
  spec.vb:
  - uid: Quickie
    name: Quickie
    href: Quickie.html
  - name: .
  - uid: Quickie.Configuration
    name: Configuration
    href: Quickie.Configuration.html
  - name: .
  - uid: Quickie.Configuration.Idempotency
    name: Idempotency
    href: Quickie.Configuration.Idempotency.html
